#!/bin/bash
links=(https://www.tldrlegal.com/license/4-clause-bsd
https://www.tldrlegal.com/license/academic-free-license-3-0-afl
https://www.tldrlegal.com/license/academy-of-motion-picture-arts-and-sciences-bsd
https://www.tldrlegal.com/license/adaptive-public-license-1-0-apl-1-0
https://www.tldrlegal.com/license/adobe-systems-incorporated-source-code-license-agreement
https://www.tldrlegal.com/license/amazon-digital-services-license
https://www.tldrlegal.com/license/android-sdk-license-agreement-june-2014
https://www.tldrlegal.com/license/apache-license-1-0-apache-1-0
https://www.tldrlegal.com/license/apache-license-2-0-apache-2-0
https://www.tldrlegal.com/license/apple-mit-license-aml
https://www.tldrlegal.com/license/apple-public-source-license-2-0-apsl
https://www.tldrlegal.com/license/apple-terms-of-service
https://www.tldrlegal.com/license/artistic-license-2-0-artistic
https://www.tldrlegal.com/license/attribution-assurance-license-aal
https://www.tldrlegal.com/license/bsd-0-clause-license
https://www.tldrlegal.com/license/bsd-2-clause-license-freebsd
https://www.tldrlegal.com/license/bsd-3-clause-license-revised
https://www.tldrlegal.com/license/beerware-license
https://www.tldrlegal.com/license/bittorrent-open-source-license-v1-1-bittorrent-1-1
https://www.tldrlegal.com/license/bodo-moeller
https://www.tldrlegal.com/license/boost-software-license-1-0-explained
https://www.tldrlegal.com/license/business-source-license-bsl-1-1
https://www.tldrlegal.com/license/cua-office-public-license-v1-0-cua-opl-1-0
https://www.tldrlegal.com/license/cecill-free-software-license-agreement-v1-0-cecill-1-0
https://www.tldrlegal.com/license/cecill-free-software-license-agreement-v1-1-cecill-1-1
https://www.tldrlegal.com/license/cecill-v2
https://www.tldrlegal.com/license/common-development-and-distribution-license-cddl-1-0-explained
https://www.tldrlegal.com/license/common-public-attribution-license-version-1-0-cpal-1-0
https://www.tldrlegal.com/license/common-public-license-1-0-cpl-1-0
https://www.tldrlegal.com/license/computer-associates-trusted-open-source-license-1-1-catosl-1-1
https://www.tldrlegal.com/license/creative-commons-attribution-cc
https://www.tldrlegal.com/license/creative-commons-attribution-4-0-international-cc-by-4
https://www.tldrlegal.com/license/creative-commons-attribution-noderivs-cc-nd
https://www.tldrlegal.com/license/creative-commons-attribution-noncommercial-cc-nc
https://www.tldrlegal.com/license/creative-commons-attribution-noncommercial-noderivs-cc-nc-nd
https://www.tldrlegal.com/license/creative-commons-attribution-noncommercial-sharealike-cc-nc-sa
https://www.tldrlegal.com/license/creative-commons-attribution-share-alike-cc-sa
https://www.tldrlegal.com/license/creative-commons-attribution-noderivatives-4-0-international-cc-by-nd-4-0
https://www.tldrlegal.com/license/creative-commons-public-license-ccpl
https://www.tldrlegal.com/license/creative-commons-attribution-noncommercial-4-0-international-cc-by-nc-4-0
https://www.tldrlegal.com/license/creative-commons-attribution-noncommercial-sharealike-4-0-international-cc-by-nc-sa-4-0
https://www.tldrlegal.com/license/creative-commons-attribution-sharealike-4-0-international-cc-by-sa-4-0
https://www.tldrlegal.com/license/creative-commons-cc0-1-0-universal
https://www.tldrlegal.com/license/cube-license
https://www.tldrlegal.com/license/do-wtf-you-want-to-public-license-v2-wtfpl-2-0
https://www.tldrlegal.com/license/doom-source-licence
https://www.tldrlegal.com/license/dropbox-terms-of-service
https://www.tldrlegal.com/license/eu-datagrid-software-license-eudatagrid
https://www.tldrlegal.com/license/eclipse-public-license-1-0-epl-1-0
https://www.tldrlegal.com/license/educational-community-license-version-2-0-ecl-2-0
https://www.tldrlegal.com/license/eiffel-forum-license-v2-0-efl-2-0
https://www.tldrlegal.com/license/entessa-public-license-v1-0-entessa
https://www.tldrlegal.com/license/erlang-public-license-v1-1-erlpl-1-1
https://www.tldrlegal.com/license/european-union-public-licence
https://www.tldrlegal.com/license/facebook-terms-of-service-statement-of-rights-and-responsibilities
https://www.tldrlegal.com/license/fair-license
https://www.tldrlegal.com/license/frameworx-open-license-1-0-frameworx-1-0
https://www.tldrlegal.com/license/free-public-license-1-0-0
https://www.tldrlegal.com/license/functional-source-license-fsl
https://www.tldrlegal.com/license/gnu-affero-general-public-license-v3-agpl-3-0
https://www.tldrlegal.com/license/gnu-free-documentation-license
https://www.tldrlegal.com/license/gnu-general-public-license-v2
https://www.tldrlegal.com/license/gnu-general-public-license-v3-gpl-3
https://www.tldrlegal.com/license/gnu-lesser-general-public-license
https://www.tldrlegal.com/license/gnu-lesser-general-public-license-v2-1-lgpl-2-1
https://www.tldrlegal.com/license/gnu-lesser-general-public-license-v3-lgpl-3
https://www.tldrlegal.com/license/historic-permission-notice-and-disclaimer-hpnd
https://www.tldrlegal.com/license/ibm-powerpc-initialization-and-boot-software-ibm-pibs
https://www.tldrlegal.com/license/ibm-public-license-1-0-ipl
https://www.tldrlegal.com/license/ipa-font-license-ipa
https://www.tldrlegal.com/license/isc-license
https://www.tldrlegal.com/license/independent-jpeg-group-license-ijg
https://www.tldrlegal.com/license/instagram-terms-of-use
https://www.tldrlegal.com/license/intel-open-source-license-intel
https://www.tldrlegal.com/license/latex-project-public-license-v1-3c-lppl-1-3c
https://www.tldrlegal.com/license/league-of-legends-terms-of-use
https://www.tldrlegal.com/license/lucent-public-license-v1-02-lpl-1-02
https://www.tldrlegal.com/license/mit-license
https://www.tldrlegal.com/license/microsoft-public-license-ms-pl
https://www.tldrlegal.com/license/microsoft-reciprocal-license-ms-rl
https://www.tldrlegal.com/license/minecraft-terms-of-service
https://www.tldrlegal.com/license/minecraft-end-user-license-agreement
https://www.tldrlegal.com/license/miros-license-miros
https://www.tldrlegal.com/license/mozilla-public-license-1-0-mpl-1-0
https://www.tldrlegal.com/license/mozilla-public-license-1-1-mpl-1-1
https://www.tldrlegal.com/license/mozilla-public-license-2-0-mpl-2
https://www.tldrlegal.com/license/multics-license-multics
https://www.tldrlegal.com/license/nasa-open-source-agreement-1-3-nasa-1-3
https://www.tldrlegal.com/license/ntp-license-ntp
https://www.tldrlegal.com/license/naumen-public-license-naumen
https://www.tldrlegal.com/license/nethack-general-public-license-ngpl
https://www.tldrlegal.com/license/netscape-public-license-v1-1-npl-1-1
https://www.tldrlegal.com/license/nokia-open-source-license-nokia-open-source-license
https://www.tldrlegal.com/license/non-profit-open-software-license-3-0-nposl-3-0
https://www.tldrlegal.com/license/oclc-research-public-license-2-0-oclc-2-0
https://www.tldrlegal.com/license/odc-open-database-license-odbl
https://www.tldrlegal.com/license/odc-public-domain-dedication-license-1-0-pddl-1-0
https://www.tldrlegal.com/license/open-group-test-suite-license-ogtsl
https://www.tldrlegal.com/license/open-public-license-v1-0-opl-1-0
https://www.tldrlegal.com/license/open-software-licence-3-0
https://www.tldrlegal.com/license/open-software-license-1-0-opl-1-0
https://www.tldrlegal.com/license/open-software-license-1-1-osl-1-1
https://www.tldrlegal.com/license/open-software-license-2-0-osl-2-0
https://www.tldrlegal.com/license/open-software-license-2-1-osl-2-1
https://www.tldrlegal.com/license/openldap-public-license-v2-8-oldap-2-8
https://www.tldrlegal.com/license/openssl-license-openssl
https://www.tldrlegal.com/license/oracle-binary-code-license-agreement-for-the-java-se-platform-products-and-javafx
https://www.tldrlegal.com/license/php-license-3-0-php
https://www.tldrlegal.com/license/the-php-license-3-0-1
https://www.tldrlegal.com/license/pokemon-go-terms-of-service
https://www.tldrlegal.com/license/postgresql-license-postgresql
https://www.tldrlegal.com/license/python-license-2-0
https://www.tldrlegal.com/license/q-public-license-1-0-qpl-1-0
https://www.tldrlegal.com/license/realnetworks-public-source-license-v1-0-rpsl-1-0
https://www.tldrlegal.com/license/reciprocal-public-license-1-5-rpl-1-5
https://www.tldrlegal.com/license/red-hat-ecos-public-license-v1-1-rhecos-1-1
https://www.tldrlegal.com/license/ricoh-source-code-public-license-rscpl
https://www.tldrlegal.com/license/ruby-license-ruby
https://www.tldrlegal.com/license/sgi-free-software-license-b-v2-0-sgi-b-2-0
https://www.tldrlegal.com/license/open-font-license-ofl-explained
https://www.tldrlegal.com/license/sax-public-domain-notice-sax-pd
https://www.tldrlegal.com/license/simple-public-license-2-0-simpl
https://www.tldrlegal.com/license/sleepycat-license
https://www.tldrlegal.com/license/snapchat-terms-of-service
https://www.tldrlegal.com/license/sun-public-license-v1-0-spl-1-0
https://www.tldrlegal.com/license/sybase-open-watcom-public-license-1-0-watcom-1-0
https://www.tldrlegal.com/license/tldrlegal-terms-of-service
https://www.tldrlegal.com/license/the-json-license
https://www.tldrlegal.com/license/universal-permissive-license-1-0-upl-1-0
https://www.tldrlegal.com/license/university-of-illinois-ncsa-open-source-license-ncsa
https://www.tldrlegal.com/license/unlicense
https://www.tldrlegal.com/license/unreal-engine-end-user-license-agreement-version-9
https://www.tldrlegal.com/license/vovida-software-license-v1-0-vsl-1-0
https://www.tldrlegal.com/license/w3c-software-notice-and-license-w3c
https://www.tldrlegal.com/license/xfree86-license-1-1-xfree86-1-1
https://www.tldrlegal.com/license/xerox-license-xerox
https://www.tldrlegal.com/license/yahoo-public-license-v1-1-ypl-1-1
https://www.tldrlegal.com/license/youtube-terms-of-service
https://www.tldrlegal.com/license/zlib-libpng-license-zlib
https://www.tldrlegal.com/license/zope-public-license-1-1-zpl-1-1
https://www.tldrlegal.com/license/zope-public-license-2-0-zpl-2-0
https://www.tldrlegal.com/license/curl-license
https://www.tldrlegal.com/license/commons-clause)

for link in "${links[@]}"; do
  curl "$link" | node tldr_page_scrape.js > "individual_licenses/$link"
done
